/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface OlympusMockGivingInterface extends ethers.utils.Interface {
  functions: {
    "DECIMALS()": FunctionFragment;
    "deposit(uint256,address)": FunctionFragment;
    "depositDisabled()": FunctionFragment;
    "depositsTo(address,address)": FunctionFragment;
    "disableDeposits(bool)": FunctionFragment;
    "disableRedeems(bool)": FunctionFragment;
    "disableWithdrawals(bool)": FunctionFragment;
    "donatedTo(address,address)": FunctionFragment;
    "donationInfo(address,uint256)": FunctionFragment;
    "emergencyShutdown(bool)": FunctionFragment;
    "getAllDeposits(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "pullManagement()": FunctionFragment;
    "pushManagement(address)": FunctionFragment;
    "recipientInfo(address)": FunctionFragment;
    "redeem()": FunctionFragment;
    "redeemDisabled()": FunctionFragment;
    "redeemableBalance(address)": FunctionFragment;
    "renounceManagement()": FunctionFragment;
    "sOHM()": FunctionFragment;
    "totalDeposits(address)": FunctionFragment;
    "totalDonated(address)": FunctionFragment;
    "withdraw(uint256,address)": FunctionFragment;
    "withdrawAll()": FunctionFragment;
    "withdrawDisabled()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "DECIMALS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositDisabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositsTo",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "disableDeposits",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "disableRedeems",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "disableWithdrawals",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "donatedTo",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "donationInfo",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyShutdown",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllDeposits",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pullManagement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pushManagement",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "recipientInfo",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "redeem", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeemDisabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeemableBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceManagement",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sOHM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalDeposits",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDonated",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawDisabled",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "DECIMALS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositDisabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositsTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disableDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableRedeems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donatedTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donationInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyShutdown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pullManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recipientInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemDisabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sOHM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDonated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDisabled",
    data: BytesLike
  ): Result;

  events: {
    "AllWithdrawn(address,uint256)": EventFragment;
    "Deposited(address,address,uint256)": EventFragment;
    "EmergencyShutdown(bool)": EventFragment;
    "OwnershipPulled(address,address)": EventFragment;
    "OwnershipPushed(address,address)": EventFragment;
    "Redeemed(address,uint256)": EventFragment;
    "Withdrawn(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AllWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EmergencyShutdown"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipPulled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipPushed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Redeemed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawn"): EventFragment;
}

export type AllWithdrawnEvent = TypedEvent<
  [string, BigNumber],
  { donor_: string; amount_: BigNumber }
>;

export type AllWithdrawnEventFilter = TypedEventFilter<AllWithdrawnEvent>;

export type DepositedEvent = TypedEvent<
  [string, string, BigNumber],
  { donor_: string; recipient_: string; amount_: BigNumber }
>;

export type DepositedEventFilter = TypedEventFilter<DepositedEvent>;

export type EmergencyShutdownEvent = TypedEvent<
  [boolean],
  { active_: boolean }
>;

export type EmergencyShutdownEventFilter =
  TypedEventFilter<EmergencyShutdownEvent>;

export type OwnershipPulledEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipPulledEventFilter = TypedEventFilter<OwnershipPulledEvent>;

export type OwnershipPushedEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipPushedEventFilter = TypedEventFilter<OwnershipPushedEvent>;

export type RedeemedEvent = TypedEvent<
  [string, BigNumber],
  { recipient_: string; amount_: BigNumber }
>;

export type RedeemedEventFilter = TypedEventFilter<RedeemedEvent>;

export type WithdrawnEvent = TypedEvent<
  [string, string, BigNumber],
  { donor_: string; recipient_: string; amount_: BigNumber }
>;

export type WithdrawnEventFilter = TypedEventFilter<WithdrawnEvent>;

export interface OlympusMockGiving extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OlympusMockGivingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DECIMALS(overrides?: CallOverrides): Promise<[BigNumber]>;

    deposit(
      amount_: BigNumberish,
      recipient_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositDisabled(overrides?: CallOverrides): Promise<[boolean]>;

    depositsTo(
      donor_: string,
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    disableDeposits(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    disableRedeems(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    disableWithdrawals(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    donatedTo(
      donor_: string,
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    donationInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        recipient: string;
        deposit: BigNumber;
        agnosticDeposit: BigNumber;
        carry: BigNumber;
        indexAtLastChange: BigNumber;
      }
    >;

    emergencyShutdown(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAllDeposits(
      donor_: string,
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber[]]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pullManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pushManagement(
      newOwner_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    recipientInfo(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        totalDebt: BigNumber;
        carry: BigNumber;
        agnosticDebt: BigNumber;
        indexAtLastChange: BigNumber;
      }
    >;

    redeem(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    redeemDisabled(overrides?: CallOverrides): Promise<[boolean]>;

    redeemableBalance(
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    renounceManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sOHM(overrides?: CallOverrides): Promise<[string]>;

    totalDeposits(
      donor_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalDonated(
      donor_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdraw(
      amount_: BigNumberish,
      recipient_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawAll(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawDisabled(overrides?: CallOverrides): Promise<[boolean]>;
  };

  DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

  deposit(
    amount_: BigNumberish,
    recipient_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositDisabled(overrides?: CallOverrides): Promise<boolean>;

  depositsTo(
    donor_: string,
    recipient_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  disableDeposits(
    active_: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  disableRedeems(
    active_: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  disableWithdrawals(
    active_: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  donatedTo(
    donor_: string,
    recipient_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  donationInfo(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      recipient: string;
      deposit: BigNumber;
      agnosticDeposit: BigNumber;
      carry: BigNumber;
      indexAtLastChange: BigNumber;
    }
  >;

  emergencyShutdown(
    active_: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAllDeposits(
    donor_: string,
    overrides?: CallOverrides
  ): Promise<[string[], BigNumber[]]>;

  owner(overrides?: CallOverrides): Promise<string>;

  pullManagement(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pushManagement(
    newOwner_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  recipientInfo(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      totalDebt: BigNumber;
      carry: BigNumber;
      agnosticDebt: BigNumber;
      indexAtLastChange: BigNumber;
    }
  >;

  redeem(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  redeemDisabled(overrides?: CallOverrides): Promise<boolean>;

  redeemableBalance(
    recipient_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  renounceManagement(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sOHM(overrides?: CallOverrides): Promise<string>;

  totalDeposits(donor_: string, overrides?: CallOverrides): Promise<BigNumber>;

  totalDonated(donor_: string, overrides?: CallOverrides): Promise<BigNumber>;

  withdraw(
    amount_: BigNumberish,
    recipient_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawAll(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawDisabled(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      amount_: BigNumberish,
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    depositDisabled(overrides?: CallOverrides): Promise<boolean>;

    depositsTo(
      donor_: string,
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    disableDeposits(active_: boolean, overrides?: CallOverrides): Promise<void>;

    disableRedeems(active_: boolean, overrides?: CallOverrides): Promise<void>;

    disableWithdrawals(
      active_: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    donatedTo(
      donor_: string,
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    donationInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        recipient: string;
        deposit: BigNumber;
        agnosticDeposit: BigNumber;
        carry: BigNumber;
        indexAtLastChange: BigNumber;
      }
    >;

    emergencyShutdown(
      active_: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllDeposits(
      donor_: string,
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber[]]>;

    owner(overrides?: CallOverrides): Promise<string>;

    pullManagement(overrides?: CallOverrides): Promise<void>;

    pushManagement(newOwner_: string, overrides?: CallOverrides): Promise<void>;

    recipientInfo(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        totalDebt: BigNumber;
        carry: BigNumber;
        agnosticDebt: BigNumber;
        indexAtLastChange: BigNumber;
      }
    >;

    redeem(overrides?: CallOverrides): Promise<void>;

    redeemDisabled(overrides?: CallOverrides): Promise<boolean>;

    redeemableBalance(
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceManagement(overrides?: CallOverrides): Promise<void>;

    sOHM(overrides?: CallOverrides): Promise<string>;

    totalDeposits(
      donor_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalDonated(donor_: string, overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      amount_: BigNumberish,
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawAll(overrides?: CallOverrides): Promise<void>;

    withdrawDisabled(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "AllWithdrawn(address,uint256)"(
      donor_?: null,
      amount_?: null
    ): AllWithdrawnEventFilter;
    AllWithdrawn(donor_?: null, amount_?: null): AllWithdrawnEventFilter;

    "Deposited(address,address,uint256)"(
      donor_?: null,
      recipient_?: null,
      amount_?: null
    ): DepositedEventFilter;
    Deposited(
      donor_?: null,
      recipient_?: null,
      amount_?: null
    ): DepositedEventFilter;

    "EmergencyShutdown(bool)"(active_?: null): EmergencyShutdownEventFilter;
    EmergencyShutdown(active_?: null): EmergencyShutdownEventFilter;

    "OwnershipPulled(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipPulledEventFilter;
    OwnershipPulled(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipPulledEventFilter;

    "OwnershipPushed(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipPushedEventFilter;
    OwnershipPushed(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipPushedEventFilter;

    "Redeemed(address,uint256)"(
      recipient_?: null,
      amount_?: null
    ): RedeemedEventFilter;
    Redeemed(recipient_?: null, amount_?: null): RedeemedEventFilter;

    "Withdrawn(address,address,uint256)"(
      donor_?: null,
      recipient_?: null,
      amount_?: null
    ): WithdrawnEventFilter;
    Withdrawn(
      donor_?: null,
      recipient_?: null,
      amount_?: null
    ): WithdrawnEventFilter;
  };

  estimateGas: {
    DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      amount_: BigNumberish,
      recipient_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositDisabled(overrides?: CallOverrides): Promise<BigNumber>;

    depositsTo(
      donor_: string,
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    disableDeposits(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    disableRedeems(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    disableWithdrawals(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    donatedTo(
      donor_: string,
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    donationInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    emergencyShutdown(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAllDeposits(
      donor_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pullManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pushManagement(
      newOwner_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    recipientInfo(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    redeem(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    redeemDisabled(overrides?: CallOverrides): Promise<BigNumber>;

    redeemableBalance(
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sOHM(overrides?: CallOverrides): Promise<BigNumber>;

    totalDeposits(
      donor_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalDonated(donor_: string, overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      amount_: BigNumberish,
      recipient_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawAll(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawDisabled(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DECIMALS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      amount_: BigNumberish,
      recipient_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositDisabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositsTo(
      donor_: string,
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    disableDeposits(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    disableRedeems(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    disableWithdrawals(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    donatedTo(
      donor_: string,
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    donationInfo(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    emergencyShutdown(
      active_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAllDeposits(
      donor_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pullManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pushManagement(
      newOwner_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    recipientInfo(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    redeem(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    redeemDisabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    redeemableBalance(
      recipient_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceManagement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sOHM(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalDeposits(
      donor_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalDonated(
      donor_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      amount_: BigNumberish,
      recipient_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawAll(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawDisabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
