/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { OlympusFaucet, OlympusFaucetInterface } from "../OlympusFaucet";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "address payable[]",
        name: "_users",
        type: "address[]",
      },
    ],
    name: "whitelistUsers",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

export class OlympusFaucet__factory {
  static readonly abi = _abi;
  static createInterface(): OlympusFaucetInterface {
    return new utils.Interface(_abi) as OlympusFaucetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OlympusFaucet {
    return new Contract(address, _abi, signerOrProvider) as OlympusFaucet;
  }
}
